name: CI
on:
  pull_request:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'tests/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   strategy:
  #     matrix:
  #       python-version: ["3.10", "3.12"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: 'pip'
  #     - run: pip install -r requirements.txt
  #     - run: pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml
  #     - uses: actions/upload-artifact@v4
  #       if: success()
  #       with:
  #         name: coverage-${{ matrix.python-version }}
  #         path: coverage.xml

  ascii:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print celebratory ASCII
        run: |
          sudo apt-get update && sudo apt-get install -y figlet
          figlet "CI PASS"
