name: Deploy to EKS
on:
  push:
    branches: [main]
    paths: ['k8s/**']
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubActionsEKSDeployRole
          aws-region: eu-central-1
      - name: Install kubectl
        run: |
          curl -sSL -o kubectl https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region eu-central-1 --name demo-eks
      - name: Apply manifests
        run: kubectl apply -f k8s/
      - name: Wait for rollout
        run: kubectl rollout status deploy/flask-demo -n default --timeout=180s
